version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    develop:
      watch:
        - action: sync
          path: .
          target: /var/www/html
          ignore:
            - .git
            - .vscode
            - vendor/
